using System.ComponentModel.DataAnnotations;
using Microsoft.EntityFrameworkCore;

namespace Example.Api;

//TODO: .AsNoTracking() by default

/// <summary>
/// npgsql (Postgres driver for EF)
/// 'ID (auto-increment)' recomendations => Type = 'long':
/// 1. https://www.npgsql.org/efcore/modeling/generated-properties.html?tabs=13%2Cefcore5
/// 2. https://www.npgsql.org/doc/types/basic.html
/// </summary>
public class WeatherContext : DbContext
{
    public WeatherContext(DbContextOptions<WeatherContext> options)
        : base(options)
    {
    }

    public required DbSet<Forecast>      Forecasts      { get; set; }// = null!;
}

public class Forecast
{
    // for pgsql - autogenerated
    // [Timestamp]
    // public uint Version { get; set; }

    // for msSql??? - autogenerated
    // [Timestamp]
    // public byte[] Version { get; set; } = [];

    // Application-managed concurrency tokens
    // [ConcurrencyCheck]
    // public Guid Version { get; set; }

    // optimistic concurrency token for pgsql
    [Timestamp]
    public /*auto*/ uint    Version { get; init; }
    public /*auto*/ long    Id      { get; init; }
    public string?  Name    { get; set; }
    public long     Count   { get; set; }
    //public Instant CreatedAt {get; set;}
}